//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animals
    {
        public long idAnimal { get; set; }
        public long idPaisNaixement { get; set; }
        public long idRecepcioBestiar { get; set; }
        public string DIB { get; set; }
        public string Sexe { get; set; }
        public string Edat { get; set; }
        public string DIBmare { get; set; }
        public Nullable<double> Pes { get; set; }
        public Nullable<int> numCarril { get; set; }
    
        public virtual paisos paisos { get; set; }
        public virtual recepcions_bestiar recepcions_bestiar { get; set; }
    }
}
