//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escorxadam2Entities : DbContext
    {
        public escorxadam2Entities()
            : base("name=escorxadam2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animals> animals { get; set; }
        public virtual DbSet<comptadors_lot_mes> comptadors_lot_mes { get; set; }
        public virtual DbSet<comunitats_autonomes> comunitats_autonomes { get; set; }
        public virtual DbSet<emmagatzematges> emmagatzematges { get; set; }
        public virtual DbSet<estables> estables { get; set; }
        public virtual DbSet<estat_estabulacions> estat_estabulacions { get; set; }
        public virtual DbSet<estat_inspeccions> estat_inspeccions { get; set; }
        public virtual DbSet<estat_processos_envasat> estat_processos_envasat { get; set; }
        public virtual DbSet<estat_processos_inicials> estat_processos_inicials { get; set; }
        public virtual DbSet<estat_refrigeracions> estat_refrigeracions { get; set; }
        public virtual DbSet<estat_sacrifici> estat_sacrifici { get; set; }
        public virtual DbSet<inspeccions> inspeccions { get; set; }
        public virtual DbSet<itemMenu> itemMenu { get; set; }
        public virtual DbSet<lots> lots { get; set; }
        public virtual DbSet<nivells_acces> nivells_acces { get; set; }
        public virtual DbSet<paisos> paisos { get; set; }
        public virtual DbSet<processats_finals> processats_finals { get; set; }
        public virtual DbSet<processats_inicials> processats_inicials { get; set; }
        public virtual DbSet<proveidors> proveidors { get; set; }
        public virtual DbSet<recepcions_bestiar> recepcions_bestiar { get; set; }
        public virtual DbSet<referencies> referencies { get; set; }
        public virtual DbSet<sacrificis> sacrificis { get; set; }
        public virtual DbSet<sistemes_atordiment> sistemes_atordiment { get; set; }
        public virtual DbSet<situacio_explotacions> situacio_explotacions { get; set; }
        public virtual DbSet<tipus_explotacions> tipus_explotacions { get; set; }
        public virtual DbSet<usuaris> usuaris { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<sitran> sitran { get; set; }
    }
}
