//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sacrificis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sacrificis()
        {
            this.lots = new HashSet<lots>();
        }
    
        public long idSacrifici { get; set; }
        public long idUsuari { get; set; }
        public long idSistemaAtordiment { get; set; }
        public long idInspeccioSanitaria { get; set; }
        public Nullable<long> idEstatSacrifici { get; set; }
        public string boxImmobilitzacio { get; set; }
        public string AparellAtordiment { get; set; }
        public System.DateTime dataSacrifici { get; set; }
        public string Incidencies { get; set; }
    
        public virtual estat_sacrifici estat_sacrifici { get; set; }
        public virtual inspeccions inspeccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lots> lots { get; set; }
        public virtual sistemes_atordiment sistemes_atordiment { get; set; }
        public virtual usuaris usuaris { get; set; }
    }
}
