//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitran
    {
        public long idSitran { get; set; }
        public string codiREGA { get; set; }
        public string tipusExplotacio { get; set; }
        public string situacioExplotacio { get; set; }
        public string tipusBestiar { get; set; }
    }
}
