//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspeccions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inspeccions()
        {
            this.estables = new HashSet<estables>();
            this.sacrificis = new HashSet<sacrificis>();
        }
    
        public long idInspeccio { get; set; }
        public long idEstatInspeccio { get; set; }
        public string codiInspeccio { get; set; }
        public string codiVeterinari { get; set; }
        public System.DateTime dataInspeccio { get; set; }
        public string descInspeccio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estables> estables { get; set; }
        public virtual estat_inspeccions estat_inspeccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sacrificis> sacrificis { get; set; }
    }
}
