//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemMenu
    {
        public long idItem { get; set; }
        public string nomItem { get; set; }
        public long ordre { get; set; }
        public string dll { get; set; }
        public string taula { get; set; }
        public string nivellAcces { get; set; }
    }
}
