//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public long idUsuari { get; set; }
        public long idNivellAcces { get; set; }
    
        public virtual nivells_acces nivells_acces { get; set; }
        public virtual usuaris usuaris { get; set; }
        public virtual usuaris usuaris1 { get; set; }
        public virtual usuaris usuaris2 { get; set; }
    }
}
