//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepcioBestiar.checkREGA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="checkREGA.SitranWSSoap")]
    public interface SitranWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rega del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckREGA", ReplyAction="*")]
        RecepcioBestiar.checkREGA.CheckREGAResponse CheckREGA(RecepcioBestiar.checkREGA.CheckREGARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckREGA", ReplyAction="*")]
        System.Threading.Tasks.Task<RecepcioBestiar.checkREGA.CheckREGAResponse> CheckREGAAsync(RecepcioBestiar.checkREGA.CheckREGARequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckREGARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckREGA", Namespace="http://tempuri.org/", Order=0)]
        public RecepcioBestiar.checkREGA.CheckREGARequestBody Body;
        
        public CheckREGARequest() {
        }
        
        public CheckREGARequest(RecepcioBestiar.checkREGA.CheckREGARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckREGARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rega;
        
        public CheckREGARequestBody() {
        }
        
        public CheckREGARequestBody(string rega) {
            this.rega = rega;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckREGAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckREGAResponse", Namespace="http://tempuri.org/", Order=0)]
        public RecepcioBestiar.checkREGA.CheckREGAResponseBody Body;
        
        public CheckREGAResponse() {
        }
        
        public CheckREGAResponse(RecepcioBestiar.checkREGA.CheckREGAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckREGAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckREGAResult;
        
        public CheckREGAResponseBody() {
        }
        
        public CheckREGAResponseBody(bool CheckREGAResult) {
            this.CheckREGAResult = CheckREGAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SitranWSSoapChannel : RecepcioBestiar.checkREGA.SitranWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SitranWSSoapClient : System.ServiceModel.ClientBase<RecepcioBestiar.checkREGA.SitranWSSoap>, RecepcioBestiar.checkREGA.SitranWSSoap {
        
        public SitranWSSoapClient() {
        }
        
        public SitranWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SitranWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitranWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitranWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecepcioBestiar.checkREGA.CheckREGAResponse RecepcioBestiar.checkREGA.SitranWSSoap.CheckREGA(RecepcioBestiar.checkREGA.CheckREGARequest request) {
            return base.Channel.CheckREGA(request);
        }
        
        public bool CheckREGA(string rega) {
            RecepcioBestiar.checkREGA.CheckREGARequest inValue = new RecepcioBestiar.checkREGA.CheckREGARequest();
            inValue.Body = new RecepcioBestiar.checkREGA.CheckREGARequestBody();
            inValue.Body.rega = rega;
            RecepcioBestiar.checkREGA.CheckREGAResponse retVal = ((RecepcioBestiar.checkREGA.SitranWSSoap)(this)).CheckREGA(inValue);
            return retVal.Body.CheckREGAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecepcioBestiar.checkREGA.CheckREGAResponse> RecepcioBestiar.checkREGA.SitranWSSoap.CheckREGAAsync(RecepcioBestiar.checkREGA.CheckREGARequest request) {
            return base.Channel.CheckREGAAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecepcioBestiar.checkREGA.CheckREGAResponse> CheckREGAAsync(string rega) {
            RecepcioBestiar.checkREGA.CheckREGARequest inValue = new RecepcioBestiar.checkREGA.CheckREGARequest();
            inValue.Body = new RecepcioBestiar.checkREGA.CheckREGARequestBody();
            inValue.Body.rega = rega;
            return ((RecepcioBestiar.checkREGA.SitranWSSoap)(this)).CheckREGAAsync(inValue);
        }
    }
}
