//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPrincipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class emmagatzematges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emmagatzematges()
        {
            this.lots = new HashSet<lots>();
        }
    
        public long idEmmagatzematge { get; set; }
        public long idEstatRefrigeracio { get; set; }
        public long idUsuariEntrada { get; set; }
        public long idUsuariSortida { get; set; }
        public int numCambraFrigorifica { get; set; }
        public System.DateTime dataEntrada { get; set; }
        public System.DateTime dataSortida { get; set; }
        public double temperaturaMaxima { get; set; }
        public double temperaturaMinima { get; set; }
    
        public virtual estat_refrigeracions estat_refrigeracions { get; set; }
        public virtual usuaris usuaris { get; set; }
        public virtual usuaris usuaris1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lots> lots { get; set; }
    }
}
