//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPrincipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class estat_processos_inicials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estat_processos_inicials()
        {
            this.processats_inicials = new HashSet<processats_inicials>();
        }
    
        public long idEstatProcesInicial { get; set; }
        public string Estat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processats_inicials> processats_inicials { get; set; }
    }
}
