//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPrincipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class processats_finals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public processats_finals()
        {
            this.lots = new HashSet<lots>();
        }
    
        public long idProcessatFinal { get; set; }
        public long idUsuari { get; set; }
        public long idSafata { get; set; }
        public long idEstatEnvasat { get; set; }
        public string DIB { get; set; }
        public System.DateTime dataEnvasat { get; set; }
        public System.DateTime diaCaducitat { get; set; }
        public double pesSafata { get; set; }
        public double percO2 { get; set; }
        public double percCO2 { get; set; }
        public double Mioglobina { get; set; }
    
        public virtual estat_processos_envasat estat_processos_envasat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lots> lots { get; set; }
        public virtual referencies referencies { get; set; }
        public virtual usuaris usuaris { get; set; }
    }
}
