//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPrincipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveidors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveidors()
        {
            this.recepcions_bestiar = new HashSet<recepcions_bestiar>();
        }
    
        public long idProveidor { get; set; }
        public long idComunitatAutonoma { get; set; }
        public long idTipusExplotacio { get; set; }
        public long idSituacioActual { get; set; }
        public string nomResponsable { get; set; }
        public string primerCognom { get; set; }
        public string segonCognom { get; set; }
        public string nomExplotacio { get; set; }
        public string direccioExplotacio { get; set; }
        public string codiExplotacio { get; set; }
    
        public virtual comunitats_autonomes comunitats_autonomes { get; set; }
        public virtual situacio_explotacions situacio_explotacions { get; set; }
        public virtual tipus_explotacions tipus_explotacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepcions_bestiar> recepcions_bestiar { get; set; }
    }
}
