//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuPrincipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class recepcions_bestiar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recepcions_bestiar()
        {
            this.animals = new HashSet<animals>();
            this.lots = new HashSet<lots>();
        }
    
        public long idRecepcio { get; set; }
        public long idUsuariReceptor { get; set; }
        public long idProveidor { get; set; }
        public string codiREMO { get; set; }
        public string codiREGA { get; set; }
        public string codiTransportista { get; set; }
        public System.DateTime dataSortidaExplotacio { get; set; }
        public System.DateTime dataEntradaEscorxador { get; set; }
        public int numTotalAnimals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<animals> animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lots> lots { get; set; }
        public virtual proveidors proveidors { get; set; }
        public virtual usuaris usuaris { get; set; }
    }
}
